### PR TITLE
Big rewrite

### PR DESCRIPTION
**Pull request by SiboVG**
This PR is a big rewrite of ampy-gui (great tool btw @dork3nergy, thanks!).

Most noticeable additions:
- Port selection dialog that allows you to quickly select the serial port of the remote device
image
- The run remote file button now works + added a run local file button (runs a local file on the remote device)
- Added button states, so buttons are disabled or enabled based on the tree view state, e.g. if the device is not yet connected, the remote buttons are disabled
- Improved terminal messages + added different colors for normal info, warning messages, or error messages
- Multi-file selection now supported (also for the functions put, get, run and delete)
- Clear terminal button
- Added a config file so that you don't have to retype the port you usually use every time
- Delay now supports 1 decimal numbers
- Connecting to a device is now **much** faster than before (previously, my application often froze for a minute, or just crashed; now my connection is set up in a couple of seconds)
- Hover-text for buttons to help understand what they do
- Probably some other stuff I forgot

Only tested on macOS 12.4, MacBook Pro M1, with an ESP32.

Small demo:

https://user-images.githubusercontent.com/11031519/183398688-c5462243-0209-4be3-b020-f5b56f9cfc3b.mov

### CODE REVIEW

**Comment by dork3nergy** [comment]
Wow! Love all the new changes and fixes.  Well done!

**Comment by SiboVG** [comment]
I can try to test it out on Windows tonight. You were not sure whether it was portable to Windows? I did replace "static" file path creation, i.e. '<directory> + "/" + <file>" with os.path.join, which should make it portable to every OS, but I'll have to do some testing. If you find other anomalies or want stuff changed, let me know :)

**Comment by dork3nergy** [comment]
I suck at all this github stuff.  There's a problem with the run command in that if the tmp path does not exist, the run errors out.  Try something like this around line 800 :

```
#Fetch the file to be run from the remote device as a temp 
#file, run that local temp file, then delete the temp file

#check if tmp path exists
if not(os.path.exists(self.progpath+"/tmp")):
	# if not, make one
	os.mkdir(self.progpath+"/tmp")



#os.path.join seems to add a /./ to the path for some reason
#Maybe just a simple concat would work fine here.
#tmp_file = os.path.join(self.progpath, "tmp", fname)

tmp_file = self.progpath+"/tmp/"+fname

self.get_file(None, terminal_buffer, usepath, tmp_file)
self.run_local_file(tmp_file, terminal_buffer)
os.remove(tmp_file)
```

**Comment by SiboVG** [comment]
> I suck at all this github stuff. There's a problem with the run command in that if the tmp path does not exist, the run errors out. Try something like this around line 800 :

Ah yeah, right, didn't notice since I already created the tmp directory, I'll take a look at it.

**Comment by dork3nergy** [comment]
I'm really appreciate you keeping this little program alive ^_^d

**Comment by SiboVG** [comment]
> I'm really appreciate you keeping this little program alive ^_^d

No probs :)

**Pull request merged**
